### ISSUE TITLE
"The message port closed before a response was received." 

### ISSUE THREAD

**Issue by MrM-7** [MrM-7/Lorem-Ipsum-Generator#1]
**This error is coming in website**   _in the console_

**Comment by MrM-7** [comment]
**Try to solve it**

**Comment by AbhishekBhatt072003** [comment]
Hey bro can I contribute to this issue. 
You can assign this to me.

**Comment by MrM-7** [comment]
Sure!!

**Comment by AbhishekBhatt072003** [comment]
Oy kyu close kiya

**Comment by MrM-7** [comment]
Kuch krne ka mann krra tha 😂
